version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: your_app
      MONGO_USER:
      MONGO_PASSWORD:
      JWT_SECRET: your_jwt_secret
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
